### ISSUE TITLE
check version number

### ISSUE THREAD

**Issue by ThierryO** [inbo/checklist#1]
- [x] allowed formats
    - 0.0
    - 0.0.0
    - 0.0.0.9000
- [x] version number is a branch must be larger than the current master
- [x] version number in master must be larger than the previous commit in master
- [x] check for tidy DESCRIPTION (`usethis::tidy_description()`)

**Comment by ThierryO** [comment]
version format 0.0.0.9000 adds to the CRAN incoming feasibility note. This makes it hard to set up a checklist.yml as it checks for identical notes. So, for the time being we will not allow the version format 0.0.0.9000.

**Comment by ThierryO** [comment]
Handled #8

**Comment by hansvancalster** [comment]
See discussion here (and above) https://github.com/inbo/protocolhelper/pull/37#issuecomment-802720557

**Comment by ThierryO** [comment]
@hansvancalster and @florisvdh please note 

> version format 0.0.0.9000 adds to the CRAN incoming feasibility note. This makes it hard to set up a checklist.yml as it checks for identical notes. So, for the time being we will not allow the version format 0.0.0.9000.

Feel free to send a PR if you really need the 0.0.0.9000 format.

**Comment by hansvancalster** [comment]
This is very likely not something I could do. I had a look at the code, but I'm pretty sure I will have overlooked lots of issues. Anyway, here are some things I noticed:


https://github.com/inbo/checklist/blob/2030bdd096122d5a6330421037d72beac2251005/inst/package_template/check_on_different_r_os.yml#L82

This line means that R CMD CHECK will not error due to format 0.0.0.9000 (since checks as cran yield a note about this)  if it were to be allowed here https://github.com/inbo/checklist/blob/2030bdd096122d5a6330421037d72beac2251005/R/check_description.R#L28 and 
here https://github.com/inbo/checklist/blob/2030bdd096122d5a6330421037d72beac2251005/R/check_cran.R#L27
?

Why `error = "never"` in `check_cran` and not `error = "warning"` as is done in `check_on_different_r_os.yml`?

**Comment by ThierryO** [comment]
`check_cran()` uses a different principle. It allows all warnings and errors. So it doesn't returns an error in case rcmdcheck detect errors or warnings. This allows to run the other checks too. We store the errors, warnings and notes in the checklist object. Once all tests from `check_package()` have run, we check the entire set of tests in the object with the objects internal `fail()` function.
https://github.com/inbo/checklist/blob/de7a9ab54d247a64d940e3c31400dea9ea9cf77b/R/check_package.R#L33 and
https://github.com/inbo/checklist/blob/2030bdd096122d5a6330421037d72beac2251005/R/checklist_class.R#L170

We compare all warnings and notes with the allowed warnings and notes. https://github.com/inbo/checklist/blob/2030bdd096122d5a6330421037d72beac2251005/R/checklist_class.R#L186
The problem is that `rcmcheck()` returns a single note with several topics (new maintainer, 0.0.0.9000 formated version number, ...). The verbatim version of the allowed notes are stored in `checklist.yml`. Allowing 0.0.0.9000 in the current implementation would require the user to update `checklist.yml` everytime they update the version number. Which is IMHO even more annoying than not be able to use 0.0.0.9000.

**Comment by hansvancalster** [comment]
Thanks for the insight on how the package works! This is really helpful. 

>Allowing 0.0.0.9000 in the current implementation would require the user to update checklist.yml everytime they update the version number. Which is IMHO even more annoying than not be able to use 0.0.0.9000.

I agree.

Would it help if: 

https://github.com/inbo/checklist/blob/2030bdd096122d5a6330421037d72beac2251005/R/check_cran.R#L24-L35

the result `check_output` is first passed to `rcmdcheck::check_details()`? According to the documentation it will return a list with (among others):
> • notes: character vector of check NOTEs, each NOTE is an element

In the hope that this will resolve the issue of 
>The problem is that rcmcheck() returns a single note with several topics (new maintainer, 0.0.0.9000 formated version number, ...).

This discussion is also relevant here: https://github.com/r-lib/devtools/issues/632

**Comment by ThierryO** [comment]
> the result `check_output` is first passed to `rcmdcheck::check_details()`? According to the documentation it will return a list with (among others):

I know that. Unfortunately, everything related to CRAN incoming feasability is in the same element.

**Comment by florisvdh** [comment]
Based on the hint in https://github.com/inbo/protocolhelper/pull/43#issuecomment-804701527, using a 0.0.0.**900** format instead of 0.0.0.**9000** could be the solution to keep both a development suffix and satisfy the CRAN incoming feasibility check.

Tried in `n2khab` using `rcmdcheck::rcmdcheck(args = c("--as-cran", "--no-manual"))` (subset called by `checklist::check_cran()`):

**With current dev version number 0.4.0.9000 (branch dev_0.5.0):**

```
N  checking CRAN incoming feasibility (2m 14.1s)
   Maintainer: ‘Floris Vanderhaeghe <floris.vanderhaeghe@inbo.be>’
   
   New submission
   
   Version contains large components (0.4.0.9000)
```

**With overwritten dev version number 0.4.0._900_ (not pushed):**

```
N  checking CRAN incoming feasibility (2m 1.7s)
   Maintainer: ‘Floris Vanderhaeghe <floris.vanderhaeghe@inbo.be>’
   
   New submission
```

**Comment by hansvancalster** [comment]
Yes, that's it! 👍

**Comment by hansvancalster** [comment]
@ThierryO is it correct that in that case you only need to change
https://github.com/inbo/checklist/blob/2030bdd096122d5a6330421037d72beac2251005/R/check_description.R#L28

to allow 0.0.0.900 format too? Something like (which also prevents numbers larger than 999):
```
!grepl("^[0-9]{1,3}\\.[0-9]{1,3}(\\.[0-9]{1,3})?(\\.[0-9]{1,3})?$", version) 
````

**Comment by florisvdh** [comment]
> Something like (which also prevents numbers larger than 999)

From the viewpoint of CRAN, which would allow dev versions numbers up to x.y.z.1234, we could even further relax this and allow the maximum allowed number of successive dev versions, i.e. going from 0.0.0.900 all the way to 0.0.0.1234 = 335 dev versions allowed between releases. (Version number ordering is different from character sorting: 0.0.0.900 < 0.0.0.1000) That would probably be enough for those who'd like to increment version numbers per commit (as is done in some software projects).

Using .900 instead of .9000 will make the usage of PR-numbers to increment the dev version number (such as .9125 when merging PR 125) practically impossible. But IMO that is a deficient approach anyway since PRs are not necessarily merged 'in order of appearance'. If you want to increase dev version numbers based on successive PR merges, I'd rather suggest .901 after the first merge since last release, .902 after the second and so on.

But we may also just allow .001, .002, etc., in which case the above becomes less relevant. However it's relevant in giving advice: _start a dev version at x.y.z.001 or at x.y.z.900_? The advantage of the larger number .900 is that it is more easily recognized as "odd", hence unofficial.

Note that .000 is not an option to start with:

```r
> package_version("0.1.0") < package_version("0.1.0.000")
[1] FALSE
> package_version("0.1.0") < package_version("0.1.0.001")
[1] TRUE
```
