### ISSUE TITLE
Add keyword `R package` in `write_zenodo_json()`

### ISSUE THREAD

**Issue by peterdesmet** [inbo/checklist#82]
`write_zenodo_json()` sets the deposit title to `package_name: Title`, e.g.:

> frictionless: Read and Write Frictionless Data Packages

Following CRAN instructions, this doesn't mention the words `R` or `package`, which is fine within the R community, but less clear outside of it (Zenodo, citations). Users can see it is software (= deposit type), but I think it could help if the keyword `R package` was added as well.

**Comment by florisvdh** [comment]
Some alternatives:

1. R package frictionless: Read and Write Frictionless Data Packages
2. frictionless R package: Read and Write Frictionless Data Packages
3. frictionless: R package to Read and Write Frictionless Data Packages 

I favour nr. 1 for readability. Nr 2 and 3 put the name at the front. Nr 3 has disadvantage of needing an extra word like 'to' and this would depend on the title, so that one won't work IMO.

**Comment by peterdesmet** [comment]
I favour having the word first. Thought at first that I wanted `R package` included in the title, but I think an automated CITATION for a package doesn't include that word either. I'd therefore opt for an `R package` keyword. Is likely the least obtrusive.

**Comment by ThierryO** [comment]
I've implemented keywords for all citation files in #85. Details is [`NEWS.md`](https://github.com/inbo/checklist/blob/bugfix/NEWS.md).

**Comment by ElsLommelen** [comment]
It seems to work fine: I tried adding keyword 'INBO database' to package `inbodb` using the explanation in NEWS.md, and 'R package' was added automatically as a keyword.  Please check on Zenodo if the output was as intended, I'm not an expert on that.  ;-)
